/* Generated by Yosys 0.57+260 (git sha1 f7120e9c2, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module \$paramod$c187add8a104ddaa470efe8146e8110778d2ccf0\mem (clk, rst_n, data_in, wtr_ptr, full, wtr_en, rd_ptr, rd_en, empty, data_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [31:0] data_in;
  wire [31:0] data_in;
  input [2:0] wtr_ptr;
  wire [2:0] wtr_ptr;
  input full;
  wire full;
  input wtr_en;
  wire wtr_en;
  input [2:0] rd_ptr;
  wire [2:0] rd_ptr;
  input rd_en;
  wire rd_en;
  input empty;
  wire empty;
  output [31:0] data_out;
  wire [31:0] data_out;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire [31:0] \mem[0] ;
  wire [31:0] \mem[1] ;
  wire [31:0] \mem[2] ;
  wire [31:0] \mem[3] ;
  wire [31:0] \mem[4] ;
  wire [31:0] \mem[5] ;
  wire [31:0] \mem[6] ;
  wire [31:0] \mem[7] ;
  sky130_fd_sc_hd__nor4bb_1 _0406_ (
    .A(wtr_ptr[0]),
    .B(full),
    .C_N(wtr_en),
    .D_N(rst_n),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__and3_1 _0407_ (
    .A(wtr_ptr[1]),
    .B(wtr_ptr[2]),
    .C(_0264_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__nand2b_1 _0408_ (
    .A_N(_0265_),
    .B(rst_n),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__and4b_1 _0409_ (
    .A_N(full),
    .B(wtr_en),
    .C(rst_n),
    .D(wtr_ptr[0]),
    .X(_0266_)
  );
  sky130_fd_sc_hd__and3_1 _0410_ (
    .A(wtr_ptr[1]),
    .B(wtr_ptr[2]),
    .C(_0266_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__nand2b_1 _0411_ (
    .A_N(_0267_),
    .B(rst_n),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0412_ (
    .A(wtr_ptr[2]),
    .SLEEP(wtr_ptr[1]),
    .X(_0268_)
  );
  sky130_fd_sc_hd__nand2_1 _0413_ (
    .A(_0266_),
    .B(_0268_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__nand2_1 _0414_ (
    .A(rst_n),
    .B(_0269_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nand2_1 _0415_ (
    .A(_0264_),
    .B(_0268_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__nand2_1 _0416_ (
    .A(rst_n),
    .B(_0270_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0417_ (
    .A(wtr_ptr[1]),
    .SLEEP(wtr_ptr[2]),
    .X(_0271_)
  );
  sky130_fd_sc_hd__nand2_1 _0418_ (
    .A(_0266_),
    .B(_0271_),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__nand2_1 _0419_ (
    .A(rst_n),
    .B(_0272_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__nand2_1 _0420_ (
    .A(_0264_),
    .B(_0271_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__nand2_1 _0421_ (
    .A(rst_n),
    .B(_0273_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__nor2_1 _0422_ (
    .A(wtr_ptr[1]),
    .B(wtr_ptr[2]),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__nand2_1 _0423_ (
    .A(_0266_),
    .B(_0274_),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__nand2_1 _0424_ (
    .A(rst_n),
    .B(_0275_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__nand2_1 _0425_ (
    .A(_0264_),
    .B(_0274_),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__nand2_1 _0426_ (
    .A(rst_n),
    .B(_0276_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0427_ (
    .A(rd_en),
    .SLEEP(empty),
    .X(_0277_)
  );
  sky130_fd_sc_hd__mux4_2 _0428_ (
    .A0(\mem[2] [0]),
    .A1(\mem[3] [0]),
    .A2(\mem[6] [0]),
    .A3(\mem[7] [0]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0278_)
  );
  sky130_fd_sc_hd__clkinv_1 _0429_ (
    .A(_0278_),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__mux4_2 _0430_ (
    .A0(\mem[0] [0]),
    .A1(\mem[1] [0]),
    .A2(\mem[4] [0]),
    .A3(\mem[5] [0]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0280_)
  );
  sky130_fd_sc_hd__o21ai_0 _0431_ (
    .A1(rd_ptr[1]),
    .A2(_0280_),
    .B1(_0277_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__a21oi_1 _0432_ (
    .A1(rd_ptr[1]),
    .A2(_0279_),
    .B1(_0281_),
    .Y(data_out[0])
  );
  sky130_fd_sc_hd__mux4_2 _0433_ (
    .A0(\mem[2] [1]),
    .A1(\mem[3] [1]),
    .A2(\mem[6] [1]),
    .A3(\mem[7] [1]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0282_)
  );
  sky130_fd_sc_hd__clkinv_1 _0434_ (
    .A(_0282_),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__mux4_2 _0435_ (
    .A0(\mem[0] [1]),
    .A1(\mem[1] [1]),
    .A2(\mem[4] [1]),
    .A3(\mem[5] [1]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0284_)
  );
  sky130_fd_sc_hd__o21ai_0 _0436_ (
    .A1(rd_ptr[1]),
    .A2(_0284_),
    .B1(_0277_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__a21oi_1 _0437_ (
    .A1(rd_ptr[1]),
    .A2(_0283_),
    .B1(_0285_),
    .Y(data_out[1])
  );
  sky130_fd_sc_hd__mux4_2 _0438_ (
    .A0(\mem[2] [2]),
    .A1(\mem[3] [2]),
    .A2(\mem[6] [2]),
    .A3(\mem[7] [2]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0286_)
  );
  sky130_fd_sc_hd__clkinv_1 _0439_ (
    .A(_0286_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__mux4_2 _0440_ (
    .A0(\mem[0] [2]),
    .A1(\mem[1] [2]),
    .A2(\mem[4] [2]),
    .A3(\mem[5] [2]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0288_)
  );
  sky130_fd_sc_hd__o21ai_0 _0441_ (
    .A1(rd_ptr[1]),
    .A2(_0288_),
    .B1(_0277_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__a21oi_1 _0442_ (
    .A1(rd_ptr[1]),
    .A2(_0287_),
    .B1(_0289_),
    .Y(data_out[2])
  );
  sky130_fd_sc_hd__mux4_2 _0443_ (
    .A0(\mem[2] [3]),
    .A1(\mem[3] [3]),
    .A2(\mem[6] [3]),
    .A3(\mem[7] [3]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0290_)
  );
  sky130_fd_sc_hd__clkinv_1 _0444_ (
    .A(_0290_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__mux4_2 _0445_ (
    .A0(\mem[0] [3]),
    .A1(\mem[1] [3]),
    .A2(\mem[4] [3]),
    .A3(\mem[5] [3]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0292_)
  );
  sky130_fd_sc_hd__o21ai_0 _0446_ (
    .A1(rd_ptr[1]),
    .A2(_0292_),
    .B1(_0277_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__a21oi_1 _0447_ (
    .A1(rd_ptr[1]),
    .A2(_0291_),
    .B1(_0293_),
    .Y(data_out[3])
  );
  sky130_fd_sc_hd__mux4_2 _0448_ (
    .A0(\mem[2] [4]),
    .A1(\mem[3] [4]),
    .A2(\mem[6] [4]),
    .A3(\mem[7] [4]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0294_)
  );
  sky130_fd_sc_hd__clkinv_1 _0449_ (
    .A(_0294_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__mux4_2 _0450_ (
    .A0(\mem[0] [4]),
    .A1(\mem[1] [4]),
    .A2(\mem[4] [4]),
    .A3(\mem[5] [4]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0296_)
  );
  sky130_fd_sc_hd__o21ai_0 _0451_ (
    .A1(rd_ptr[1]),
    .A2(_0296_),
    .B1(_0277_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__a21oi_1 _0452_ (
    .A1(rd_ptr[1]),
    .A2(_0295_),
    .B1(_0297_),
    .Y(data_out[4])
  );
  sky130_fd_sc_hd__mux4_2 _0453_ (
    .A0(\mem[2] [5]),
    .A1(\mem[3] [5]),
    .A2(\mem[6] [5]),
    .A3(\mem[7] [5]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0298_)
  );
  sky130_fd_sc_hd__clkinv_1 _0454_ (
    .A(_0298_),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__mux4_2 _0455_ (
    .A0(\mem[0] [5]),
    .A1(\mem[1] [5]),
    .A2(\mem[4] [5]),
    .A3(\mem[5] [5]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0300_)
  );
  sky130_fd_sc_hd__o21ai_0 _0456_ (
    .A1(rd_ptr[1]),
    .A2(_0300_),
    .B1(_0277_),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__a21oi_1 _0457_ (
    .A1(rd_ptr[1]),
    .A2(_0299_),
    .B1(_0301_),
    .Y(data_out[5])
  );
  sky130_fd_sc_hd__mux4_2 _0458_ (
    .A0(\mem[2] [6]),
    .A1(\mem[3] [6]),
    .A2(\mem[6] [6]),
    .A3(\mem[7] [6]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0302_)
  );
  sky130_fd_sc_hd__clkinv_1 _0459_ (
    .A(_0302_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__mux4_2 _0460_ (
    .A0(\mem[0] [6]),
    .A1(\mem[1] [6]),
    .A2(\mem[4] [6]),
    .A3(\mem[5] [6]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0304_)
  );
  sky130_fd_sc_hd__o21ai_0 _0461_ (
    .A1(rd_ptr[1]),
    .A2(_0304_),
    .B1(_0277_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__a21oi_1 _0462_ (
    .A1(rd_ptr[1]),
    .A2(_0303_),
    .B1(_0305_),
    .Y(data_out[6])
  );
  sky130_fd_sc_hd__mux4_2 _0463_ (
    .A0(\mem[2] [7]),
    .A1(\mem[3] [7]),
    .A2(\mem[6] [7]),
    .A3(\mem[7] [7]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0306_)
  );
  sky130_fd_sc_hd__clkinv_1 _0464_ (
    .A(_0306_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__mux4_2 _0465_ (
    .A0(\mem[0] [7]),
    .A1(\mem[1] [7]),
    .A2(\mem[4] [7]),
    .A3(\mem[5] [7]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0308_)
  );
  sky130_fd_sc_hd__o21ai_0 _0466_ (
    .A1(rd_ptr[1]),
    .A2(_0308_),
    .B1(_0277_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__a21oi_1 _0467_ (
    .A1(rd_ptr[1]),
    .A2(_0307_),
    .B1(_0309_),
    .Y(data_out[7])
  );
  sky130_fd_sc_hd__mux4_2 _0468_ (
    .A0(\mem[2] [8]),
    .A1(\mem[3] [8]),
    .A2(\mem[6] [8]),
    .A3(\mem[7] [8]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0310_)
  );
  sky130_fd_sc_hd__clkinv_1 _0469_ (
    .A(_0310_),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__mux4_2 _0470_ (
    .A0(\mem[0] [8]),
    .A1(\mem[1] [8]),
    .A2(\mem[4] [8]),
    .A3(\mem[5] [8]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0312_)
  );
  sky130_fd_sc_hd__o21ai_0 _0471_ (
    .A1(rd_ptr[1]),
    .A2(_0312_),
    .B1(_0277_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__a21oi_1 _0472_ (
    .A1(rd_ptr[1]),
    .A2(_0311_),
    .B1(_0313_),
    .Y(data_out[8])
  );
  sky130_fd_sc_hd__mux4_2 _0473_ (
    .A0(\mem[2] [9]),
    .A1(\mem[3] [9]),
    .A2(\mem[6] [9]),
    .A3(\mem[7] [9]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0314_)
  );
  sky130_fd_sc_hd__clkinv_1 _0474_ (
    .A(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__mux4_2 _0475_ (
    .A0(\mem[0] [9]),
    .A1(\mem[1] [9]),
    .A2(\mem[4] [9]),
    .A3(\mem[5] [9]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0316_)
  );
  sky130_fd_sc_hd__o21ai_0 _0476_ (
    .A1(rd_ptr[1]),
    .A2(_0316_),
    .B1(_0277_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__a21oi_1 _0477_ (
    .A1(rd_ptr[1]),
    .A2(_0315_),
    .B1(_0317_),
    .Y(data_out[9])
  );
  sky130_fd_sc_hd__mux4_2 _0478_ (
    .A0(\mem[2] [10]),
    .A1(\mem[3] [10]),
    .A2(\mem[6] [10]),
    .A3(\mem[7] [10]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0318_)
  );
  sky130_fd_sc_hd__clkinv_1 _0479_ (
    .A(_0318_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__mux4_2 _0480_ (
    .A0(\mem[0] [10]),
    .A1(\mem[1] [10]),
    .A2(\mem[4] [10]),
    .A3(\mem[5] [10]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0320_)
  );
  sky130_fd_sc_hd__o21ai_0 _0481_ (
    .A1(rd_ptr[1]),
    .A2(_0320_),
    .B1(_0277_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__a21oi_1 _0482_ (
    .A1(rd_ptr[1]),
    .A2(_0319_),
    .B1(_0321_),
    .Y(data_out[10])
  );
  sky130_fd_sc_hd__mux4_2 _0483_ (
    .A0(\mem[2] [11]),
    .A1(\mem[3] [11]),
    .A2(\mem[6] [11]),
    .A3(\mem[7] [11]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0322_)
  );
  sky130_fd_sc_hd__clkinv_1 _0484_ (
    .A(_0322_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__mux4_2 _0485_ (
    .A0(\mem[0] [11]),
    .A1(\mem[1] [11]),
    .A2(\mem[4] [11]),
    .A3(\mem[5] [11]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0324_)
  );
  sky130_fd_sc_hd__o21ai_0 _0486_ (
    .A1(rd_ptr[1]),
    .A2(_0324_),
    .B1(_0277_),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__a21oi_1 _0487_ (
    .A1(rd_ptr[1]),
    .A2(_0323_),
    .B1(_0325_),
    .Y(data_out[11])
  );
  sky130_fd_sc_hd__mux4_2 _0488_ (
    .A0(\mem[2] [12]),
    .A1(\mem[3] [12]),
    .A2(\mem[6] [12]),
    .A3(\mem[7] [12]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0326_)
  );
  sky130_fd_sc_hd__clkinv_1 _0489_ (
    .A(_0326_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__mux4_2 _0490_ (
    .A0(\mem[0] [12]),
    .A1(\mem[1] [12]),
    .A2(\mem[4] [12]),
    .A3(\mem[5] [12]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0328_)
  );
  sky130_fd_sc_hd__o21ai_0 _0491_ (
    .A1(rd_ptr[1]),
    .A2(_0328_),
    .B1(_0277_),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__a21oi_1 _0492_ (
    .A1(rd_ptr[1]),
    .A2(_0327_),
    .B1(_0329_),
    .Y(data_out[12])
  );
  sky130_fd_sc_hd__mux4_2 _0493_ (
    .A0(\mem[2] [13]),
    .A1(\mem[3] [13]),
    .A2(\mem[6] [13]),
    .A3(\mem[7] [13]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0330_)
  );
  sky130_fd_sc_hd__clkinv_1 _0494_ (
    .A(_0330_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__mux4_2 _0495_ (
    .A0(\mem[0] [13]),
    .A1(\mem[1] [13]),
    .A2(\mem[4] [13]),
    .A3(\mem[5] [13]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0332_)
  );
  sky130_fd_sc_hd__o21ai_0 _0496_ (
    .A1(rd_ptr[1]),
    .A2(_0332_),
    .B1(_0277_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__a21oi_1 _0497_ (
    .A1(rd_ptr[1]),
    .A2(_0331_),
    .B1(_0333_),
    .Y(data_out[13])
  );
  sky130_fd_sc_hd__mux4_2 _0498_ (
    .A0(\mem[2] [14]),
    .A1(\mem[3] [14]),
    .A2(\mem[6] [14]),
    .A3(\mem[7] [14]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0334_)
  );
  sky130_fd_sc_hd__clkinv_1 _0499_ (
    .A(_0334_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__mux4_2 _0500_ (
    .A0(\mem[0] [14]),
    .A1(\mem[1] [14]),
    .A2(\mem[4] [14]),
    .A3(\mem[5] [14]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0336_)
  );
  sky130_fd_sc_hd__o21ai_0 _0501_ (
    .A1(rd_ptr[1]),
    .A2(_0336_),
    .B1(_0277_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__a21oi_1 _0502_ (
    .A1(rd_ptr[1]),
    .A2(_0335_),
    .B1(_0337_),
    .Y(data_out[14])
  );
  sky130_fd_sc_hd__mux4_2 _0503_ (
    .A0(\mem[2] [15]),
    .A1(\mem[3] [15]),
    .A2(\mem[6] [15]),
    .A3(\mem[7] [15]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0338_)
  );
  sky130_fd_sc_hd__clkinv_1 _0504_ (
    .A(_0338_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__mux4_2 _0505_ (
    .A0(\mem[0] [15]),
    .A1(\mem[1] [15]),
    .A2(\mem[4] [15]),
    .A3(\mem[5] [15]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0340_)
  );
  sky130_fd_sc_hd__o21ai_0 _0506_ (
    .A1(rd_ptr[1]),
    .A2(_0340_),
    .B1(_0277_),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__a21oi_1 _0507_ (
    .A1(rd_ptr[1]),
    .A2(_0339_),
    .B1(_0341_),
    .Y(data_out[15])
  );
  sky130_fd_sc_hd__mux4_2 _0508_ (
    .A0(\mem[2] [16]),
    .A1(\mem[3] [16]),
    .A2(\mem[6] [16]),
    .A3(\mem[7] [16]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0342_)
  );
  sky130_fd_sc_hd__clkinv_1 _0509_ (
    .A(_0342_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__mux4_2 _0510_ (
    .A0(\mem[0] [16]),
    .A1(\mem[1] [16]),
    .A2(\mem[4] [16]),
    .A3(\mem[5] [16]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0344_)
  );
  sky130_fd_sc_hd__o21ai_0 _0511_ (
    .A1(rd_ptr[1]),
    .A2(_0344_),
    .B1(_0277_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__a21oi_1 _0512_ (
    .A1(rd_ptr[1]),
    .A2(_0343_),
    .B1(_0345_),
    .Y(data_out[16])
  );
  sky130_fd_sc_hd__mux4_2 _0513_ (
    .A0(\mem[2] [17]),
    .A1(\mem[3] [17]),
    .A2(\mem[6] [17]),
    .A3(\mem[7] [17]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0346_)
  );
  sky130_fd_sc_hd__clkinv_1 _0514_ (
    .A(_0346_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__mux4_2 _0515_ (
    .A0(\mem[0] [17]),
    .A1(\mem[1] [17]),
    .A2(\mem[4] [17]),
    .A3(\mem[5] [17]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0348_)
  );
  sky130_fd_sc_hd__o21ai_0 _0516_ (
    .A1(rd_ptr[1]),
    .A2(_0348_),
    .B1(_0277_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__a21oi_1 _0517_ (
    .A1(rd_ptr[1]),
    .A2(_0347_),
    .B1(_0349_),
    .Y(data_out[17])
  );
  sky130_fd_sc_hd__mux4_2 _0518_ (
    .A0(\mem[2] [18]),
    .A1(\mem[3] [18]),
    .A2(\mem[6] [18]),
    .A3(\mem[7] [18]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0350_)
  );
  sky130_fd_sc_hd__clkinv_1 _0519_ (
    .A(_0350_),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__mux4_2 _0520_ (
    .A0(\mem[0] [18]),
    .A1(\mem[1] [18]),
    .A2(\mem[4] [18]),
    .A3(\mem[5] [18]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0352_)
  );
  sky130_fd_sc_hd__o21ai_0 _0521_ (
    .A1(rd_ptr[1]),
    .A2(_0352_),
    .B1(_0277_),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__a21oi_1 _0522_ (
    .A1(rd_ptr[1]),
    .A2(_0351_),
    .B1(_0353_),
    .Y(data_out[18])
  );
  sky130_fd_sc_hd__mux4_2 _0523_ (
    .A0(\mem[2] [19]),
    .A1(\mem[3] [19]),
    .A2(\mem[6] [19]),
    .A3(\mem[7] [19]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0354_)
  );
  sky130_fd_sc_hd__clkinv_1 _0524_ (
    .A(_0354_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__mux4_2 _0525_ (
    .A0(\mem[0] [19]),
    .A1(\mem[1] [19]),
    .A2(\mem[4] [19]),
    .A3(\mem[5] [19]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0356_)
  );
  sky130_fd_sc_hd__o21ai_0 _0526_ (
    .A1(rd_ptr[1]),
    .A2(_0356_),
    .B1(_0277_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__a21oi_1 _0527_ (
    .A1(rd_ptr[1]),
    .A2(_0355_),
    .B1(_0357_),
    .Y(data_out[19])
  );
  sky130_fd_sc_hd__mux4_2 _0528_ (
    .A0(\mem[2] [20]),
    .A1(\mem[3] [20]),
    .A2(\mem[6] [20]),
    .A3(\mem[7] [20]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0358_)
  );
  sky130_fd_sc_hd__clkinv_1 _0529_ (
    .A(_0358_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__mux4_2 _0530_ (
    .A0(\mem[0] [20]),
    .A1(\mem[1] [20]),
    .A2(\mem[4] [20]),
    .A3(\mem[5] [20]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0360_)
  );
  sky130_fd_sc_hd__o21ai_0 _0531_ (
    .A1(rd_ptr[1]),
    .A2(_0360_),
    .B1(_0277_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__a21oi_1 _0532_ (
    .A1(rd_ptr[1]),
    .A2(_0359_),
    .B1(_0361_),
    .Y(data_out[20])
  );
  sky130_fd_sc_hd__mux4_2 _0533_ (
    .A0(\mem[2] [21]),
    .A1(\mem[3] [21]),
    .A2(\mem[6] [21]),
    .A3(\mem[7] [21]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0362_)
  );
  sky130_fd_sc_hd__clkinv_1 _0534_ (
    .A(_0362_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__mux4_2 _0535_ (
    .A0(\mem[0] [21]),
    .A1(\mem[1] [21]),
    .A2(\mem[4] [21]),
    .A3(\mem[5] [21]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0364_)
  );
  sky130_fd_sc_hd__o21ai_0 _0536_ (
    .A1(rd_ptr[1]),
    .A2(_0364_),
    .B1(_0277_),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__a21oi_1 _0537_ (
    .A1(rd_ptr[1]),
    .A2(_0363_),
    .B1(_0365_),
    .Y(data_out[21])
  );
  sky130_fd_sc_hd__mux4_2 _0538_ (
    .A0(\mem[2] [22]),
    .A1(\mem[3] [22]),
    .A2(\mem[6] [22]),
    .A3(\mem[7] [22]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0366_)
  );
  sky130_fd_sc_hd__clkinv_1 _0539_ (
    .A(_0366_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__mux4_2 _0540_ (
    .A0(\mem[0] [22]),
    .A1(\mem[1] [22]),
    .A2(\mem[4] [22]),
    .A3(\mem[5] [22]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0368_)
  );
  sky130_fd_sc_hd__o21ai_0 _0541_ (
    .A1(rd_ptr[1]),
    .A2(_0368_),
    .B1(_0277_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__a21oi_1 _0542_ (
    .A1(rd_ptr[1]),
    .A2(_0367_),
    .B1(_0369_),
    .Y(data_out[22])
  );
  sky130_fd_sc_hd__mux4_2 _0543_ (
    .A0(\mem[2] [23]),
    .A1(\mem[3] [23]),
    .A2(\mem[6] [23]),
    .A3(\mem[7] [23]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0370_)
  );
  sky130_fd_sc_hd__clkinv_1 _0544_ (
    .A(_0370_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__mux4_2 _0545_ (
    .A0(\mem[0] [23]),
    .A1(\mem[1] [23]),
    .A2(\mem[4] [23]),
    .A3(\mem[5] [23]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0372_)
  );
  sky130_fd_sc_hd__o21ai_0 _0546_ (
    .A1(rd_ptr[1]),
    .A2(_0372_),
    .B1(_0277_),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__a21oi_1 _0547_ (
    .A1(rd_ptr[1]),
    .A2(_0371_),
    .B1(_0373_),
    .Y(data_out[23])
  );
  sky130_fd_sc_hd__mux4_2 _0548_ (
    .A0(\mem[2] [24]),
    .A1(\mem[3] [24]),
    .A2(\mem[6] [24]),
    .A3(\mem[7] [24]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0374_)
  );
  sky130_fd_sc_hd__clkinv_1 _0549_ (
    .A(_0374_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__mux4_2 _0550_ (
    .A0(\mem[0] [24]),
    .A1(\mem[1] [24]),
    .A2(\mem[4] [24]),
    .A3(\mem[5] [24]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0376_)
  );
  sky130_fd_sc_hd__o21ai_0 _0551_ (
    .A1(rd_ptr[1]),
    .A2(_0376_),
    .B1(_0277_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__a21oi_1 _0552_ (
    .A1(rd_ptr[1]),
    .A2(_0375_),
    .B1(_0377_),
    .Y(data_out[24])
  );
  sky130_fd_sc_hd__mux4_2 _0553_ (
    .A0(\mem[2] [25]),
    .A1(\mem[3] [25]),
    .A2(\mem[6] [25]),
    .A3(\mem[7] [25]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0378_)
  );
  sky130_fd_sc_hd__clkinv_1 _0554_ (
    .A(_0378_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__mux4_2 _0555_ (
    .A0(\mem[0] [25]),
    .A1(\mem[1] [25]),
    .A2(\mem[4] [25]),
    .A3(\mem[5] [25]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0380_)
  );
  sky130_fd_sc_hd__o21ai_0 _0556_ (
    .A1(rd_ptr[1]),
    .A2(_0380_),
    .B1(_0277_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__a21oi_1 _0557_ (
    .A1(rd_ptr[1]),
    .A2(_0379_),
    .B1(_0381_),
    .Y(data_out[25])
  );
  sky130_fd_sc_hd__mux4_2 _0558_ (
    .A0(\mem[2] [26]),
    .A1(\mem[3] [26]),
    .A2(\mem[6] [26]),
    .A3(\mem[7] [26]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0382_)
  );
  sky130_fd_sc_hd__clkinv_1 _0559_ (
    .A(_0382_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__mux4_2 _0560_ (
    .A0(\mem[0] [26]),
    .A1(\mem[1] [26]),
    .A2(\mem[4] [26]),
    .A3(\mem[5] [26]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0384_)
  );
  sky130_fd_sc_hd__o21ai_0 _0561_ (
    .A1(rd_ptr[1]),
    .A2(_0384_),
    .B1(_0277_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__a21oi_1 _0562_ (
    .A1(rd_ptr[1]),
    .A2(_0383_),
    .B1(_0385_),
    .Y(data_out[26])
  );
  sky130_fd_sc_hd__mux4_2 _0563_ (
    .A0(\mem[2] [27]),
    .A1(\mem[3] [27]),
    .A2(\mem[6] [27]),
    .A3(\mem[7] [27]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0386_)
  );
  sky130_fd_sc_hd__clkinv_1 _0564_ (
    .A(_0386_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__mux4_2 _0565_ (
    .A0(\mem[0] [27]),
    .A1(\mem[1] [27]),
    .A2(\mem[4] [27]),
    .A3(\mem[5] [27]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0388_)
  );
  sky130_fd_sc_hd__o21ai_0 _0566_ (
    .A1(rd_ptr[1]),
    .A2(_0388_),
    .B1(_0277_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__a21oi_1 _0567_ (
    .A1(rd_ptr[1]),
    .A2(_0387_),
    .B1(_0389_),
    .Y(data_out[27])
  );
  sky130_fd_sc_hd__mux4_2 _0568_ (
    .A0(\mem[2] [28]),
    .A1(\mem[3] [28]),
    .A2(\mem[6] [28]),
    .A3(\mem[7] [28]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0390_)
  );
  sky130_fd_sc_hd__clkinv_1 _0569_ (
    .A(_0390_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__mux4_2 _0570_ (
    .A0(\mem[0] [28]),
    .A1(\mem[1] [28]),
    .A2(\mem[4] [28]),
    .A3(\mem[5] [28]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0392_)
  );
  sky130_fd_sc_hd__o21ai_0 _0571_ (
    .A1(rd_ptr[1]),
    .A2(_0392_),
    .B1(_0277_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__a21oi_1 _0572_ (
    .A1(rd_ptr[1]),
    .A2(_0391_),
    .B1(_0393_),
    .Y(data_out[28])
  );
  sky130_fd_sc_hd__mux4_2 _0573_ (
    .A0(\mem[2] [29]),
    .A1(\mem[3] [29]),
    .A2(\mem[6] [29]),
    .A3(\mem[7] [29]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0394_)
  );
  sky130_fd_sc_hd__clkinv_1 _0574_ (
    .A(_0394_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__mux4_2 _0575_ (
    .A0(\mem[0] [29]),
    .A1(\mem[1] [29]),
    .A2(\mem[4] [29]),
    .A3(\mem[5] [29]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0396_)
  );
  sky130_fd_sc_hd__o21ai_0 _0576_ (
    .A1(rd_ptr[1]),
    .A2(_0396_),
    .B1(_0277_),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__a21oi_1 _0577_ (
    .A1(rd_ptr[1]),
    .A2(_0395_),
    .B1(_0397_),
    .Y(data_out[29])
  );
  sky130_fd_sc_hd__mux4_2 _0578_ (
    .A0(\mem[2] [30]),
    .A1(\mem[3] [30]),
    .A2(\mem[6] [30]),
    .A3(\mem[7] [30]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0398_)
  );
  sky130_fd_sc_hd__clkinv_1 _0579_ (
    .A(_0398_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__mux4_2 _0580_ (
    .A0(\mem[0] [30]),
    .A1(\mem[1] [30]),
    .A2(\mem[4] [30]),
    .A3(\mem[5] [30]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0400_)
  );
  sky130_fd_sc_hd__o21ai_0 _0581_ (
    .A1(rd_ptr[1]),
    .A2(_0400_),
    .B1(_0277_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__a21oi_1 _0582_ (
    .A1(rd_ptr[1]),
    .A2(_0399_),
    .B1(_0401_),
    .Y(data_out[30])
  );
  sky130_fd_sc_hd__mux4_2 _0583_ (
    .A0(\mem[2] [31]),
    .A1(\mem[3] [31]),
    .A2(\mem[6] [31]),
    .A3(\mem[7] [31]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0402_)
  );
  sky130_fd_sc_hd__clkinv_1 _0584_ (
    .A(_0402_),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__mux4_2 _0585_ (
    .A0(\mem[0] [31]),
    .A1(\mem[1] [31]),
    .A2(\mem[4] [31]),
    .A3(\mem[5] [31]),
    .S0(rd_ptr[0]),
    .S1(rd_ptr[2]),
    .X(_0404_)
  );
  sky130_fd_sc_hd__o21ai_0 _0586_ (
    .A1(rd_ptr[1]),
    .A2(_0404_),
    .B1(_0277_),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__a21oi_1 _0587_ (
    .A1(rd_ptr[1]),
    .A2(_0403_),
    .B1(_0405_),
    .Y(data_out[31])
  );
  sky130_fd_sc_hd__and3_1 _0588_ (
    .A(data_in[0]),
    .B(_0264_),
    .C(_0271_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__and3_1 _0589_ (
    .A(data_in[1]),
    .B(_0264_),
    .C(_0271_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__and3_1 _0590_ (
    .A(data_in[2]),
    .B(_0264_),
    .C(_0271_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__and3_1 _0591_ (
    .A(data_in[3]),
    .B(_0264_),
    .C(_0271_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__and3_1 _0592_ (
    .A(data_in[4]),
    .B(_0264_),
    .C(_0271_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__and3_1 _0593_ (
    .A(data_in[5]),
    .B(_0264_),
    .C(_0271_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__and3_1 _0594_ (
    .A(data_in[6]),
    .B(_0264_),
    .C(_0271_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__and3_1 _0595_ (
    .A(data_in[7]),
    .B(_0264_),
    .C(_0271_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__and3_1 _0596_ (
    .A(data_in[8]),
    .B(_0264_),
    .C(_0271_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__and3_1 _0597_ (
    .A(data_in[9]),
    .B(_0264_),
    .C(_0271_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__and3_1 _0598_ (
    .A(data_in[10]),
    .B(_0264_),
    .C(_0271_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__and3_1 _0599_ (
    .A(data_in[11]),
    .B(_0264_),
    .C(_0271_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__and3_1 _0600_ (
    .A(data_in[12]),
    .B(_0264_),
    .C(_0271_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__and3_1 _0601_ (
    .A(data_in[13]),
    .B(_0264_),
    .C(_0271_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__and3_1 _0602_ (
    .A(data_in[14]),
    .B(_0264_),
    .C(_0271_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__and3_1 _0603_ (
    .A(data_in[15]),
    .B(_0264_),
    .C(_0271_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__and3_1 _0604_ (
    .A(data_in[16]),
    .B(_0264_),
    .C(_0271_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__and3_1 _0605_ (
    .A(data_in[17]),
    .B(_0264_),
    .C(_0271_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__and3_1 _0606_ (
    .A(data_in[18]),
    .B(_0264_),
    .C(_0271_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__and3_1 _0607_ (
    .A(data_in[19]),
    .B(_0264_),
    .C(_0271_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__and3_1 _0608_ (
    .A(data_in[20]),
    .B(_0264_),
    .C(_0271_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__and3_1 _0609_ (
    .A(data_in[21]),
    .B(_0264_),
    .C(_0271_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__and3_1 _0610_ (
    .A(data_in[22]),
    .B(_0264_),
    .C(_0271_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__and3_1 _0611_ (
    .A(data_in[23]),
    .B(_0264_),
    .C(_0271_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__and3_1 _0612_ (
    .A(data_in[24]),
    .B(_0264_),
    .C(_0271_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__and3_1 _0613_ (
    .A(data_in[25]),
    .B(_0264_),
    .C(_0271_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__and3_1 _0614_ (
    .A(data_in[26]),
    .B(_0264_),
    .C(_0271_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__and3_1 _0615_ (
    .A(data_in[27]),
    .B(_0264_),
    .C(_0271_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__and3_1 _0616_ (
    .A(data_in[28]),
    .B(_0264_),
    .C(_0271_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__and3_1 _0617_ (
    .A(data_in[29]),
    .B(_0264_),
    .C(_0271_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__and3_1 _0618_ (
    .A(data_in[30]),
    .B(_0264_),
    .C(_0271_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__and3_1 _0619_ (
    .A(data_in[31]),
    .B(_0264_),
    .C(_0271_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__and3_1 _0620_ (
    .A(data_in[0]),
    .B(_0264_),
    .C(_0268_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__and3_1 _0621_ (
    .A(data_in[1]),
    .B(_0264_),
    .C(_0268_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__and3_1 _0622_ (
    .A(data_in[2]),
    .B(_0264_),
    .C(_0268_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__and3_1 _0623_ (
    .A(data_in[3]),
    .B(_0264_),
    .C(_0268_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__and3_1 _0624_ (
    .A(data_in[4]),
    .B(_0264_),
    .C(_0268_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__and3_1 _0625_ (
    .A(data_in[5]),
    .B(_0264_),
    .C(_0268_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__and3_1 _0626_ (
    .A(data_in[6]),
    .B(_0264_),
    .C(_0268_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__and3_1 _0627_ (
    .A(data_in[7]),
    .B(_0264_),
    .C(_0268_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__and3_1 _0628_ (
    .A(data_in[8]),
    .B(_0264_),
    .C(_0268_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__and3_1 _0629_ (
    .A(data_in[9]),
    .B(_0264_),
    .C(_0268_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__and3_1 _0630_ (
    .A(data_in[10]),
    .B(_0264_),
    .C(_0268_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__and3_1 _0631_ (
    .A(data_in[11]),
    .B(_0264_),
    .C(_0268_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__and3_1 _0632_ (
    .A(data_in[12]),
    .B(_0264_),
    .C(_0268_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__and3_1 _0633_ (
    .A(data_in[13]),
    .B(_0264_),
    .C(_0268_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__and3_1 _0634_ (
    .A(data_in[14]),
    .B(_0264_),
    .C(_0268_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__and3_1 _0635_ (
    .A(data_in[15]),
    .B(_0264_),
    .C(_0268_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__and3_1 _0636_ (
    .A(data_in[16]),
    .B(_0264_),
    .C(_0268_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__and3_1 _0637_ (
    .A(data_in[17]),
    .B(_0264_),
    .C(_0268_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__and3_1 _0638_ (
    .A(data_in[18]),
    .B(_0264_),
    .C(_0268_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__and3_1 _0639_ (
    .A(data_in[19]),
    .B(_0264_),
    .C(_0268_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__and3_1 _0640_ (
    .A(data_in[20]),
    .B(_0264_),
    .C(_0268_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__and3_1 _0641_ (
    .A(data_in[21]),
    .B(_0264_),
    .C(_0268_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__and3_1 _0642_ (
    .A(data_in[22]),
    .B(_0264_),
    .C(_0268_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__and3_1 _0643_ (
    .A(data_in[23]),
    .B(_0264_),
    .C(_0268_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__and3_1 _0644_ (
    .A(data_in[24]),
    .B(_0264_),
    .C(_0268_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__and3_1 _0645_ (
    .A(data_in[25]),
    .B(_0264_),
    .C(_0268_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__and3_1 _0646_ (
    .A(data_in[26]),
    .B(_0264_),
    .C(_0268_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__and3_1 _0647_ (
    .A(data_in[27]),
    .B(_0264_),
    .C(_0268_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__and3_1 _0648_ (
    .A(data_in[28]),
    .B(_0264_),
    .C(_0268_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__and3_1 _0649_ (
    .A(data_in[29]),
    .B(_0264_),
    .C(_0268_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__and3_1 _0650_ (
    .A(data_in[30]),
    .B(_0264_),
    .C(_0268_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__and3_1 _0651_ (
    .A(data_in[31]),
    .B(_0264_),
    .C(_0268_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__and3_1 _0652_ (
    .A(data_in[0]),
    .B(_0266_),
    .C(_0271_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__and3_1 _0653_ (
    .A(data_in[1]),
    .B(_0266_),
    .C(_0271_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__and3_1 _0654_ (
    .A(data_in[2]),
    .B(_0266_),
    .C(_0271_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__and3_1 _0655_ (
    .A(data_in[3]),
    .B(_0266_),
    .C(_0271_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__and3_1 _0656_ (
    .A(data_in[4]),
    .B(_0266_),
    .C(_0271_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__and3_1 _0657_ (
    .A(data_in[5]),
    .B(_0266_),
    .C(_0271_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__and3_1 _0658_ (
    .A(data_in[6]),
    .B(_0266_),
    .C(_0271_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__and3_1 _0659_ (
    .A(data_in[7]),
    .B(_0266_),
    .C(_0271_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__and3_1 _0660_ (
    .A(data_in[8]),
    .B(_0266_),
    .C(_0271_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__and3_1 _0661_ (
    .A(data_in[9]),
    .B(_0266_),
    .C(_0271_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__and3_1 _0662_ (
    .A(data_in[10]),
    .B(_0266_),
    .C(_0271_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__and3_1 _0663_ (
    .A(data_in[11]),
    .B(_0266_),
    .C(_0271_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__and3_1 _0664_ (
    .A(data_in[12]),
    .B(_0266_),
    .C(_0271_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__and3_1 _0665_ (
    .A(data_in[13]),
    .B(_0266_),
    .C(_0271_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__and3_1 _0666_ (
    .A(data_in[14]),
    .B(_0266_),
    .C(_0271_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__and3_1 _0667_ (
    .A(data_in[15]),
    .B(_0266_),
    .C(_0271_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__and3_1 _0668_ (
    .A(data_in[16]),
    .B(_0266_),
    .C(_0271_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__and3_1 _0669_ (
    .A(data_in[17]),
    .B(_0266_),
    .C(_0271_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__and3_1 _0670_ (
    .A(data_in[18]),
    .B(_0266_),
    .C(_0271_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__and3_1 _0671_ (
    .A(data_in[19]),
    .B(_0266_),
    .C(_0271_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__and3_1 _0672_ (
    .A(data_in[20]),
    .B(_0266_),
    .C(_0271_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__and3_1 _0673_ (
    .A(data_in[21]),
    .B(_0266_),
    .C(_0271_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__and3_1 _0674_ (
    .A(data_in[22]),
    .B(_0266_),
    .C(_0271_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__and3_1 _0675_ (
    .A(data_in[23]),
    .B(_0266_),
    .C(_0271_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__and3_1 _0676_ (
    .A(data_in[24]),
    .B(_0266_),
    .C(_0271_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__and3_1 _0677_ (
    .A(data_in[25]),
    .B(_0266_),
    .C(_0271_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__and3_1 _0678_ (
    .A(data_in[26]),
    .B(_0266_),
    .C(_0271_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__and3_1 _0679_ (
    .A(data_in[27]),
    .B(_0266_),
    .C(_0271_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__and3_1 _0680_ (
    .A(data_in[28]),
    .B(_0266_),
    .C(_0271_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__and3_1 _0681_ (
    .A(data_in[29]),
    .B(_0266_),
    .C(_0271_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__and3_1 _0682_ (
    .A(data_in[30]),
    .B(_0266_),
    .C(_0271_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__and3_1 _0683_ (
    .A(data_in[31]),
    .B(_0266_),
    .C(_0271_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__and2_0 _0684_ (
    .A(data_in[0]),
    .B(_0265_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__and2_0 _0685_ (
    .A(data_in[1]),
    .B(_0265_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__and2_0 _0686_ (
    .A(data_in[2]),
    .B(_0265_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__and2_0 _0687_ (
    .A(data_in[3]),
    .B(_0265_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__and2_0 _0688_ (
    .A(data_in[4]),
    .B(_0265_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__and2_0 _0689_ (
    .A(data_in[5]),
    .B(_0265_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__and2_0 _0690_ (
    .A(data_in[6]),
    .B(_0265_),
    .X(_0110_)
  );
  sky130_fd_sc_hd__and2_0 _0691_ (
    .A(data_in[7]),
    .B(_0265_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__and2_0 _0692_ (
    .A(data_in[8]),
    .B(_0265_),
    .X(_0112_)
  );
  sky130_fd_sc_hd__and2_0 _0693_ (
    .A(data_in[9]),
    .B(_0265_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__and2_0 _0694_ (
    .A(data_in[10]),
    .B(_0265_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__and2_0 _0695_ (
    .A(data_in[11]),
    .B(_0265_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__and2_0 _0696_ (
    .A(data_in[12]),
    .B(_0265_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__and2_0 _0697_ (
    .A(data_in[13]),
    .B(_0265_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__and2_0 _0698_ (
    .A(data_in[14]),
    .B(_0265_),
    .X(_0118_)
  );
  sky130_fd_sc_hd__and2_0 _0699_ (
    .A(data_in[15]),
    .B(_0265_),
    .X(_0119_)
  );
  sky130_fd_sc_hd__and2_0 _0700_ (
    .A(data_in[16]),
    .B(_0265_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__and2_0 _0701_ (
    .A(data_in[17]),
    .B(_0265_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__and2_0 _0702_ (
    .A(data_in[18]),
    .B(_0265_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__and2_0 _0703_ (
    .A(data_in[19]),
    .B(_0265_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__and2_0 _0704_ (
    .A(data_in[20]),
    .B(_0265_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__and2_0 _0705_ (
    .A(data_in[21]),
    .B(_0265_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__and2_0 _0706_ (
    .A(data_in[22]),
    .B(_0265_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__and2_0 _0707_ (
    .A(data_in[23]),
    .B(_0265_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__and2_0 _0708_ (
    .A(data_in[24]),
    .B(_0265_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__and2_0 _0709_ (
    .A(data_in[25]),
    .B(_0265_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__and2_0 _0710_ (
    .A(data_in[26]),
    .B(_0265_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__and2_0 _0711_ (
    .A(data_in[27]),
    .B(_0265_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__and2_0 _0712_ (
    .A(data_in[28]),
    .B(_0265_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__and2_0 _0713_ (
    .A(data_in[29]),
    .B(_0265_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__and2_0 _0714_ (
    .A(data_in[30]),
    .B(_0265_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__and2_0 _0715_ (
    .A(data_in[31]),
    .B(_0265_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__and3_1 _0716_ (
    .A(data_in[0]),
    .B(_0264_),
    .C(_0274_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__and3_1 _0717_ (
    .A(data_in[1]),
    .B(_0264_),
    .C(_0274_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__and3_1 _0718_ (
    .A(data_in[2]),
    .B(_0264_),
    .C(_0274_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__and3_1 _0719_ (
    .A(data_in[3]),
    .B(_0264_),
    .C(_0274_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__and3_1 _0720_ (
    .A(data_in[4]),
    .B(_0264_),
    .C(_0274_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__and3_1 _0721_ (
    .A(data_in[5]),
    .B(_0264_),
    .C(_0274_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__and3_1 _0722_ (
    .A(data_in[6]),
    .B(_0264_),
    .C(_0274_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__and3_1 _0723_ (
    .A(data_in[7]),
    .B(_0264_),
    .C(_0274_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__and3_1 _0724_ (
    .A(data_in[8]),
    .B(_0264_),
    .C(_0274_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__and3_1 _0725_ (
    .A(data_in[9]),
    .B(_0264_),
    .C(_0274_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__and3_1 _0726_ (
    .A(data_in[10]),
    .B(_0264_),
    .C(_0274_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__and3_1 _0727_ (
    .A(data_in[11]),
    .B(_0264_),
    .C(_0274_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__and3_1 _0728_ (
    .A(data_in[12]),
    .B(_0264_),
    .C(_0274_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__and3_1 _0729_ (
    .A(data_in[13]),
    .B(_0264_),
    .C(_0274_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__and3_1 _0730_ (
    .A(data_in[14]),
    .B(_0264_),
    .C(_0274_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__and3_1 _0731_ (
    .A(data_in[15]),
    .B(_0264_),
    .C(_0274_),
    .X(_0151_)
  );
  sky130_fd_sc_hd__and3_1 _0732_ (
    .A(data_in[16]),
    .B(_0264_),
    .C(_0274_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__and3_1 _0733_ (
    .A(data_in[17]),
    .B(_0264_),
    .C(_0274_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__and3_1 _0734_ (
    .A(data_in[18]),
    .B(_0264_),
    .C(_0274_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__and3_1 _0735_ (
    .A(data_in[19]),
    .B(_0264_),
    .C(_0274_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__and3_1 _0736_ (
    .A(data_in[20]),
    .B(_0264_),
    .C(_0274_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__and3_1 _0737_ (
    .A(data_in[21]),
    .B(_0264_),
    .C(_0274_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__and3_1 _0738_ (
    .A(data_in[22]),
    .B(_0264_),
    .C(_0274_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__and3_1 _0739_ (
    .A(data_in[23]),
    .B(_0264_),
    .C(_0274_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__and3_1 _0740_ (
    .A(data_in[24]),
    .B(_0264_),
    .C(_0274_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__and3_1 _0741_ (
    .A(data_in[25]),
    .B(_0264_),
    .C(_0274_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__and3_1 _0742_ (
    .A(data_in[26]),
    .B(_0264_),
    .C(_0274_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__and3_1 _0743_ (
    .A(data_in[27]),
    .B(_0264_),
    .C(_0274_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__and3_1 _0744_ (
    .A(data_in[28]),
    .B(_0264_),
    .C(_0274_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__and3_1 _0745_ (
    .A(data_in[29]),
    .B(_0264_),
    .C(_0274_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__and3_1 _0746_ (
    .A(data_in[30]),
    .B(_0264_),
    .C(_0274_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__and3_1 _0747_ (
    .A(data_in[31]),
    .B(_0264_),
    .C(_0274_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__and3_1 _0748_ (
    .A(data_in[0]),
    .B(_0266_),
    .C(_0268_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__and3_1 _0749_ (
    .A(data_in[1]),
    .B(_0266_),
    .C(_0268_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__and3_1 _0750_ (
    .A(data_in[2]),
    .B(_0266_),
    .C(_0268_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__and3_1 _0751_ (
    .A(data_in[3]),
    .B(_0266_),
    .C(_0268_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__and3_1 _0752_ (
    .A(data_in[4]),
    .B(_0266_),
    .C(_0268_),
    .X(_0172_)
  );
  sky130_fd_sc_hd__and3_1 _0753_ (
    .A(data_in[5]),
    .B(_0266_),
    .C(_0268_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__and3_1 _0754_ (
    .A(data_in[6]),
    .B(_0266_),
    .C(_0268_),
    .X(_0174_)
  );
  sky130_fd_sc_hd__and3_1 _0755_ (
    .A(data_in[7]),
    .B(_0266_),
    .C(_0268_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__and3_1 _0756_ (
    .A(data_in[8]),
    .B(_0266_),
    .C(_0268_),
    .X(_0176_)
  );
  sky130_fd_sc_hd__and3_1 _0757_ (
    .A(data_in[9]),
    .B(_0266_),
    .C(_0268_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__and3_1 _0758_ (
    .A(data_in[10]),
    .B(_0266_),
    .C(_0268_),
    .X(_0178_)
  );
  sky130_fd_sc_hd__and3_1 _0759_ (
    .A(data_in[11]),
    .B(_0266_),
    .C(_0268_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__and3_1 _0760_ (
    .A(data_in[12]),
    .B(_0266_),
    .C(_0268_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__and3_1 _0761_ (
    .A(data_in[13]),
    .B(_0266_),
    .C(_0268_),
    .X(_0181_)
  );
  sky130_fd_sc_hd__and3_1 _0762_ (
    .A(data_in[14]),
    .B(_0266_),
    .C(_0268_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__and3_1 _0763_ (
    .A(data_in[15]),
    .B(_0266_),
    .C(_0268_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__and3_1 _0764_ (
    .A(data_in[16]),
    .B(_0266_),
    .C(_0268_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__and3_1 _0765_ (
    .A(data_in[17]),
    .B(_0266_),
    .C(_0268_),
    .X(_0185_)
  );
  sky130_fd_sc_hd__and3_1 _0766_ (
    .A(data_in[18]),
    .B(_0266_),
    .C(_0268_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__and3_1 _0767_ (
    .A(data_in[19]),
    .B(_0266_),
    .C(_0268_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__and3_1 _0768_ (
    .A(data_in[20]),
    .B(_0266_),
    .C(_0268_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__and3_1 _0769_ (
    .A(data_in[21]),
    .B(_0266_),
    .C(_0268_),
    .X(_0189_)
  );
  sky130_fd_sc_hd__and3_1 _0770_ (
    .A(data_in[22]),
    .B(_0266_),
    .C(_0268_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__and3_1 _0771_ (
    .A(data_in[23]),
    .B(_0266_),
    .C(_0268_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__and3_1 _0772_ (
    .A(data_in[24]),
    .B(_0266_),
    .C(_0268_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__and3_1 _0773_ (
    .A(data_in[25]),
    .B(_0266_),
    .C(_0268_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__and3_1 _0774_ (
    .A(data_in[26]),
    .B(_0266_),
    .C(_0268_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__and3_1 _0775_ (
    .A(data_in[27]),
    .B(_0266_),
    .C(_0268_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__and3_1 _0776_ (
    .A(data_in[28]),
    .B(_0266_),
    .C(_0268_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__and3_1 _0777_ (
    .A(data_in[29]),
    .B(_0266_),
    .C(_0268_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__and3_1 _0778_ (
    .A(data_in[30]),
    .B(_0266_),
    .C(_0268_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__and3_1 _0779_ (
    .A(data_in[31]),
    .B(_0266_),
    .C(_0268_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__and3_1 _0780_ (
    .A(data_in[0]),
    .B(_0266_),
    .C(_0274_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__and3_1 _0781_ (
    .A(data_in[1]),
    .B(_0266_),
    .C(_0274_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__and3_1 _0782_ (
    .A(data_in[2]),
    .B(_0266_),
    .C(_0274_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__and3_1 _0783_ (
    .A(data_in[3]),
    .B(_0266_),
    .C(_0274_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__and3_1 _0784_ (
    .A(data_in[4]),
    .B(_0266_),
    .C(_0274_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__and3_1 _0785_ (
    .A(data_in[5]),
    .B(_0266_),
    .C(_0274_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__and3_1 _0786_ (
    .A(data_in[6]),
    .B(_0266_),
    .C(_0274_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__and3_1 _0787_ (
    .A(data_in[7]),
    .B(_0266_),
    .C(_0274_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__and3_1 _0788_ (
    .A(data_in[8]),
    .B(_0266_),
    .C(_0274_),
    .X(_0208_)
  );
  sky130_fd_sc_hd__and3_1 _0789_ (
    .A(data_in[9]),
    .B(_0266_),
    .C(_0274_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__and3_1 _0790_ (
    .A(data_in[10]),
    .B(_0266_),
    .C(_0274_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__and3_1 _0791_ (
    .A(data_in[11]),
    .B(_0266_),
    .C(_0274_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__and3_1 _0792_ (
    .A(data_in[12]),
    .B(_0266_),
    .C(_0274_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__and3_1 _0793_ (
    .A(data_in[13]),
    .B(_0266_),
    .C(_0274_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__and3_1 _0794_ (
    .A(data_in[14]),
    .B(_0266_),
    .C(_0274_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__and3_1 _0795_ (
    .A(data_in[15]),
    .B(_0266_),
    .C(_0274_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__and3_1 _0796_ (
    .A(data_in[16]),
    .B(_0266_),
    .C(_0274_),
    .X(_0216_)
  );
  sky130_fd_sc_hd__and3_1 _0797_ (
    .A(data_in[17]),
    .B(_0266_),
    .C(_0274_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__and3_1 _0798_ (
    .A(data_in[18]),
    .B(_0266_),
    .C(_0274_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__and3_1 _0799_ (
    .A(data_in[19]),
    .B(_0266_),
    .C(_0274_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__and3_1 _0800_ (
    .A(data_in[20]),
    .B(_0266_),
    .C(_0274_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__and3_1 _0801_ (
    .A(data_in[21]),
    .B(_0266_),
    .C(_0274_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__and3_1 _0802_ (
    .A(data_in[22]),
    .B(_0266_),
    .C(_0274_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__and3_1 _0803_ (
    .A(data_in[23]),
    .B(_0266_),
    .C(_0274_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__and3_1 _0804_ (
    .A(data_in[24]),
    .B(_0266_),
    .C(_0274_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__and3_1 _0805_ (
    .A(data_in[25]),
    .B(_0266_),
    .C(_0274_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__and3_1 _0806_ (
    .A(data_in[26]),
    .B(_0266_),
    .C(_0274_),
    .X(_0226_)
  );
  sky130_fd_sc_hd__and3_1 _0807_ (
    .A(data_in[27]),
    .B(_0266_),
    .C(_0274_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__and3_1 _0808_ (
    .A(data_in[28]),
    .B(_0266_),
    .C(_0274_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__and3_1 _0809_ (
    .A(data_in[29]),
    .B(_0266_),
    .C(_0274_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__and3_1 _0810_ (
    .A(data_in[30]),
    .B(_0266_),
    .C(_0274_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__and3_1 _0811_ (
    .A(data_in[31]),
    .B(_0266_),
    .C(_0274_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__and2_0 _0812_ (
    .A(data_in[0]),
    .B(_0267_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__and2_0 _0813_ (
    .A(data_in[1]),
    .B(_0267_),
    .X(_0233_)
  );
  sky130_fd_sc_hd__and2_0 _0814_ (
    .A(data_in[2]),
    .B(_0267_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__and2_0 _0815_ (
    .A(data_in[3]),
    .B(_0267_),
    .X(_0235_)
  );
  sky130_fd_sc_hd__and2_0 _0816_ (
    .A(data_in[4]),
    .B(_0267_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__and2_0 _0817_ (
    .A(data_in[5]),
    .B(_0267_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__and2_0 _0818_ (
    .A(data_in[6]),
    .B(_0267_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__and2_0 _0819_ (
    .A(data_in[7]),
    .B(_0267_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__and2_0 _0820_ (
    .A(data_in[8]),
    .B(_0267_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__and2_0 _0821_ (
    .A(data_in[9]),
    .B(_0267_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__and2_0 _0822_ (
    .A(data_in[10]),
    .B(_0267_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__and2_0 _0823_ (
    .A(data_in[11]),
    .B(_0267_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__and2_0 _0824_ (
    .A(data_in[12]),
    .B(_0267_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__and2_0 _0825_ (
    .A(data_in[13]),
    .B(_0267_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__and2_0 _0826_ (
    .A(data_in[14]),
    .B(_0267_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__and2_0 _0827_ (
    .A(data_in[15]),
    .B(_0267_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__and2_0 _0828_ (
    .A(data_in[16]),
    .B(_0267_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__and2_0 _0829_ (
    .A(data_in[17]),
    .B(_0267_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__and2_0 _0830_ (
    .A(data_in[18]),
    .B(_0267_),
    .X(_0250_)
  );
  sky130_fd_sc_hd__and2_0 _0831_ (
    .A(data_in[19]),
    .B(_0267_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__and2_0 _0832_ (
    .A(data_in[20]),
    .B(_0267_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__and2_0 _0833_ (
    .A(data_in[21]),
    .B(_0267_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__and2_0 _0834_ (
    .A(data_in[22]),
    .B(_0267_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__and2_0 _0835_ (
    .A(data_in[23]),
    .B(_0267_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__and2_0 _0836_ (
    .A(data_in[24]),
    .B(_0267_),
    .X(_0256_)
  );
  sky130_fd_sc_hd__and2_0 _0837_ (
    .A(data_in[25]),
    .B(_0267_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__and2_0 _0838_ (
    .A(data_in[26]),
    .B(_0267_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__and2_0 _0839_ (
    .A(data_in[27]),
    .B(_0267_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__and2_0 _0840_ (
    .A(data_in[28]),
    .B(_0267_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__and2_0 _0841_ (
    .A(data_in[29]),
    .B(_0267_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__and2_0 _0842_ (
    .A(data_in[30]),
    .B(_0267_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__and2_0 _0843_ (
    .A(data_in[31]),
    .B(_0267_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__edfxtp_1 _0844_ (
    .CLK(clk),
    .D(_0008_),
    .DE(_0005_),
    .Q(\mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _0845_ (
    .CLK(clk),
    .D(_0009_),
    .DE(_0005_),
    .Q(\mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _0846_ (
    .CLK(clk),
    .D(_0010_),
    .DE(_0005_),
    .Q(\mem[2] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _0847_ (
    .CLK(clk),
    .D(_0011_),
    .DE(_0005_),
    .Q(\mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _0848_ (
    .CLK(clk),
    .D(_0012_),
    .DE(_0005_),
    .Q(\mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _0849_ (
    .CLK(clk),
    .D(_0013_),
    .DE(_0005_),
    .Q(\mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _0850_ (
    .CLK(clk),
    .D(_0014_),
    .DE(_0005_),
    .Q(\mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _0851_ (
    .CLK(clk),
    .D(_0015_),
    .DE(_0005_),
    .Q(\mem[2] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _0852_ (
    .CLK(clk),
    .D(_0016_),
    .DE(_0005_),
    .Q(\mem[2] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _0853_ (
    .CLK(clk),
    .D(_0017_),
    .DE(_0005_),
    .Q(\mem[2] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _0854_ (
    .CLK(clk),
    .D(_0018_),
    .DE(_0005_),
    .Q(\mem[2] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _0855_ (
    .CLK(clk),
    .D(_0019_),
    .DE(_0005_),
    .Q(\mem[2] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _0856_ (
    .CLK(clk),
    .D(_0020_),
    .DE(_0005_),
    .Q(\mem[2] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _0857_ (
    .CLK(clk),
    .D(_0021_),
    .DE(_0005_),
    .Q(\mem[2] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _0858_ (
    .CLK(clk),
    .D(_0022_),
    .DE(_0005_),
    .Q(\mem[2] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _0859_ (
    .CLK(clk),
    .D(_0023_),
    .DE(_0005_),
    .Q(\mem[2] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _0860_ (
    .CLK(clk),
    .D(_0024_),
    .DE(_0005_),
    .Q(\mem[2] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _0861_ (
    .CLK(clk),
    .D(_0025_),
    .DE(_0005_),
    .Q(\mem[2] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _0862_ (
    .CLK(clk),
    .D(_0026_),
    .DE(_0005_),
    .Q(\mem[2] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _0863_ (
    .CLK(clk),
    .D(_0027_),
    .DE(_0005_),
    .Q(\mem[2] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _0864_ (
    .CLK(clk),
    .D(_0028_),
    .DE(_0005_),
    .Q(\mem[2] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _0865_ (
    .CLK(clk),
    .D(_0029_),
    .DE(_0005_),
    .Q(\mem[2] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _0866_ (
    .CLK(clk),
    .D(_0030_),
    .DE(_0005_),
    .Q(\mem[2] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _0867_ (
    .CLK(clk),
    .D(_0031_),
    .DE(_0005_),
    .Q(\mem[2] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _0868_ (
    .CLK(clk),
    .D(_0032_),
    .DE(_0005_),
    .Q(\mem[2] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _0869_ (
    .CLK(clk),
    .D(_0033_),
    .DE(_0005_),
    .Q(\mem[2] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _0870_ (
    .CLK(clk),
    .D(_0034_),
    .DE(_0005_),
    .Q(\mem[2] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _0871_ (
    .CLK(clk),
    .D(_0035_),
    .DE(_0005_),
    .Q(\mem[2] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _0872_ (
    .CLK(clk),
    .D(_0036_),
    .DE(_0005_),
    .Q(\mem[2] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _0873_ (
    .CLK(clk),
    .D(_0037_),
    .DE(_0005_),
    .Q(\mem[2] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _0874_ (
    .CLK(clk),
    .D(_0038_),
    .DE(_0005_),
    .Q(\mem[2] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _0875_ (
    .CLK(clk),
    .D(_0039_),
    .DE(_0005_),
    .Q(\mem[2] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _0876_ (
    .CLK(clk),
    .D(_0040_),
    .DE(_0003_),
    .Q(\mem[4] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _0877_ (
    .CLK(clk),
    .D(_0041_),
    .DE(_0003_),
    .Q(\mem[4] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _0878_ (
    .CLK(clk),
    .D(_0042_),
    .DE(_0003_),
    .Q(\mem[4] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _0879_ (
    .CLK(clk),
    .D(_0043_),
    .DE(_0003_),
    .Q(\mem[4] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _0880_ (
    .CLK(clk),
    .D(_0044_),
    .DE(_0003_),
    .Q(\mem[4] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _0881_ (
    .CLK(clk),
    .D(_0045_),
    .DE(_0003_),
    .Q(\mem[4] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _0882_ (
    .CLK(clk),
    .D(_0046_),
    .DE(_0003_),
    .Q(\mem[4] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _0883_ (
    .CLK(clk),
    .D(_0047_),
    .DE(_0003_),
    .Q(\mem[4] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _0884_ (
    .CLK(clk),
    .D(_0048_),
    .DE(_0003_),
    .Q(\mem[4] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _0885_ (
    .CLK(clk),
    .D(_0049_),
    .DE(_0003_),
    .Q(\mem[4] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _0886_ (
    .CLK(clk),
    .D(_0050_),
    .DE(_0003_),
    .Q(\mem[4] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _0887_ (
    .CLK(clk),
    .D(_0051_),
    .DE(_0003_),
    .Q(\mem[4] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _0888_ (
    .CLK(clk),
    .D(_0052_),
    .DE(_0003_),
    .Q(\mem[4] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _0889_ (
    .CLK(clk),
    .D(_0053_),
    .DE(_0003_),
    .Q(\mem[4] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _0890_ (
    .CLK(clk),
    .D(_0054_),
    .DE(_0003_),
    .Q(\mem[4] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _0891_ (
    .CLK(clk),
    .D(_0055_),
    .DE(_0003_),
    .Q(\mem[4] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _0892_ (
    .CLK(clk),
    .D(_0056_),
    .DE(_0003_),
    .Q(\mem[4] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _0893_ (
    .CLK(clk),
    .D(_0057_),
    .DE(_0003_),
    .Q(\mem[4] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _0894_ (
    .CLK(clk),
    .D(_0058_),
    .DE(_0003_),
    .Q(\mem[4] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _0895_ (
    .CLK(clk),
    .D(_0059_),
    .DE(_0003_),
    .Q(\mem[4] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _0896_ (
    .CLK(clk),
    .D(_0060_),
    .DE(_0003_),
    .Q(\mem[4] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _0897_ (
    .CLK(clk),
    .D(_0061_),
    .DE(_0003_),
    .Q(\mem[4] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _0898_ (
    .CLK(clk),
    .D(_0062_),
    .DE(_0003_),
    .Q(\mem[4] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _0899_ (
    .CLK(clk),
    .D(_0063_),
    .DE(_0003_),
    .Q(\mem[4] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _0900_ (
    .CLK(clk),
    .D(_0064_),
    .DE(_0003_),
    .Q(\mem[4] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _0901_ (
    .CLK(clk),
    .D(_0065_),
    .DE(_0003_),
    .Q(\mem[4] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _0902_ (
    .CLK(clk),
    .D(_0066_),
    .DE(_0003_),
    .Q(\mem[4] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _0903_ (
    .CLK(clk),
    .D(_0067_),
    .DE(_0003_),
    .Q(\mem[4] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _0904_ (
    .CLK(clk),
    .D(_0068_),
    .DE(_0003_),
    .Q(\mem[4] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _0905_ (
    .CLK(clk),
    .D(_0069_),
    .DE(_0003_),
    .Q(\mem[4] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _0906_ (
    .CLK(clk),
    .D(_0070_),
    .DE(_0003_),
    .Q(\mem[4] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _0907_ (
    .CLK(clk),
    .D(_0071_),
    .DE(_0003_),
    .Q(\mem[4] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _0908_ (
    .CLK(clk),
    .D(_0072_),
    .DE(_0004_),
    .Q(\mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _0909_ (
    .CLK(clk),
    .D(_0073_),
    .DE(_0004_),
    .Q(\mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _0910_ (
    .CLK(clk),
    .D(_0074_),
    .DE(_0004_),
    .Q(\mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _0911_ (
    .CLK(clk),
    .D(_0075_),
    .DE(_0004_),
    .Q(\mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _0912_ (
    .CLK(clk),
    .D(_0076_),
    .DE(_0004_),
    .Q(\mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _0913_ (
    .CLK(clk),
    .D(_0077_),
    .DE(_0004_),
    .Q(\mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _0914_ (
    .CLK(clk),
    .D(_0078_),
    .DE(_0004_),
    .Q(\mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _0915_ (
    .CLK(clk),
    .D(_0079_),
    .DE(_0004_),
    .Q(\mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _0916_ (
    .CLK(clk),
    .D(_0080_),
    .DE(_0004_),
    .Q(\mem[3] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _0917_ (
    .CLK(clk),
    .D(_0081_),
    .DE(_0004_),
    .Q(\mem[3] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _0918_ (
    .CLK(clk),
    .D(_0082_),
    .DE(_0004_),
    .Q(\mem[3] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _0919_ (
    .CLK(clk),
    .D(_0083_),
    .DE(_0004_),
    .Q(\mem[3] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _0920_ (
    .CLK(clk),
    .D(_0084_),
    .DE(_0004_),
    .Q(\mem[3] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _0921_ (
    .CLK(clk),
    .D(_0085_),
    .DE(_0004_),
    .Q(\mem[3] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _0922_ (
    .CLK(clk),
    .D(_0086_),
    .DE(_0004_),
    .Q(\mem[3] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _0923_ (
    .CLK(clk),
    .D(_0087_),
    .DE(_0004_),
    .Q(\mem[3] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _0924_ (
    .CLK(clk),
    .D(_0088_),
    .DE(_0004_),
    .Q(\mem[3] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _0925_ (
    .CLK(clk),
    .D(_0089_),
    .DE(_0004_),
    .Q(\mem[3] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _0926_ (
    .CLK(clk),
    .D(_0090_),
    .DE(_0004_),
    .Q(\mem[3] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _0927_ (
    .CLK(clk),
    .D(_0091_),
    .DE(_0004_),
    .Q(\mem[3] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _0928_ (
    .CLK(clk),
    .D(_0092_),
    .DE(_0004_),
    .Q(\mem[3] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _0929_ (
    .CLK(clk),
    .D(_0093_),
    .DE(_0004_),
    .Q(\mem[3] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _0930_ (
    .CLK(clk),
    .D(_0094_),
    .DE(_0004_),
    .Q(\mem[3] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _0931_ (
    .CLK(clk),
    .D(_0095_),
    .DE(_0004_),
    .Q(\mem[3] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _0932_ (
    .CLK(clk),
    .D(_0096_),
    .DE(_0004_),
    .Q(\mem[3] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _0933_ (
    .CLK(clk),
    .D(_0097_),
    .DE(_0004_),
    .Q(\mem[3] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _0934_ (
    .CLK(clk),
    .D(_0098_),
    .DE(_0004_),
    .Q(\mem[3] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _0935_ (
    .CLK(clk),
    .D(_0099_),
    .DE(_0004_),
    .Q(\mem[3] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _0936_ (
    .CLK(clk),
    .D(_0100_),
    .DE(_0004_),
    .Q(\mem[3] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _0937_ (
    .CLK(clk),
    .D(_0101_),
    .DE(_0004_),
    .Q(\mem[3] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _0938_ (
    .CLK(clk),
    .D(_0102_),
    .DE(_0004_),
    .Q(\mem[3] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _0939_ (
    .CLK(clk),
    .D(_0103_),
    .DE(_0004_),
    .Q(\mem[3] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _0940_ (
    .CLK(clk),
    .D(_0104_),
    .DE(_0001_),
    .Q(\mem[6] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _0941_ (
    .CLK(clk),
    .D(_0105_),
    .DE(_0001_),
    .Q(\mem[6] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _0942_ (
    .CLK(clk),
    .D(_0106_),
    .DE(_0001_),
    .Q(\mem[6] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _0943_ (
    .CLK(clk),
    .D(_0107_),
    .DE(_0001_),
    .Q(\mem[6] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _0944_ (
    .CLK(clk),
    .D(_0108_),
    .DE(_0001_),
    .Q(\mem[6] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _0945_ (
    .CLK(clk),
    .D(_0109_),
    .DE(_0001_),
    .Q(\mem[6] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _0946_ (
    .CLK(clk),
    .D(_0110_),
    .DE(_0001_),
    .Q(\mem[6] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _0947_ (
    .CLK(clk),
    .D(_0111_),
    .DE(_0001_),
    .Q(\mem[6] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _0948_ (
    .CLK(clk),
    .D(_0112_),
    .DE(_0001_),
    .Q(\mem[6] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _0949_ (
    .CLK(clk),
    .D(_0113_),
    .DE(_0001_),
    .Q(\mem[6] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _0950_ (
    .CLK(clk),
    .D(_0114_),
    .DE(_0001_),
    .Q(\mem[6] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _0951_ (
    .CLK(clk),
    .D(_0115_),
    .DE(_0001_),
    .Q(\mem[6] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _0952_ (
    .CLK(clk),
    .D(_0116_),
    .DE(_0001_),
    .Q(\mem[6] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _0953_ (
    .CLK(clk),
    .D(_0117_),
    .DE(_0001_),
    .Q(\mem[6] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _0954_ (
    .CLK(clk),
    .D(_0118_),
    .DE(_0001_),
    .Q(\mem[6] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _0955_ (
    .CLK(clk),
    .D(_0119_),
    .DE(_0001_),
    .Q(\mem[6] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _0956_ (
    .CLK(clk),
    .D(_0120_),
    .DE(_0001_),
    .Q(\mem[6] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _0957_ (
    .CLK(clk),
    .D(_0121_),
    .DE(_0001_),
    .Q(\mem[6] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _0958_ (
    .CLK(clk),
    .D(_0122_),
    .DE(_0001_),
    .Q(\mem[6] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _0959_ (
    .CLK(clk),
    .D(_0123_),
    .DE(_0001_),
    .Q(\mem[6] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _0960_ (
    .CLK(clk),
    .D(_0124_),
    .DE(_0001_),
    .Q(\mem[6] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _0961_ (
    .CLK(clk),
    .D(_0125_),
    .DE(_0001_),
    .Q(\mem[6] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _0962_ (
    .CLK(clk),
    .D(_0126_),
    .DE(_0001_),
    .Q(\mem[6] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _0963_ (
    .CLK(clk),
    .D(_0127_),
    .DE(_0001_),
    .Q(\mem[6] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _0964_ (
    .CLK(clk),
    .D(_0128_),
    .DE(_0001_),
    .Q(\mem[6] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _0965_ (
    .CLK(clk),
    .D(_0129_),
    .DE(_0001_),
    .Q(\mem[6] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _0966_ (
    .CLK(clk),
    .D(_0130_),
    .DE(_0001_),
    .Q(\mem[6] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _0967_ (
    .CLK(clk),
    .D(_0131_),
    .DE(_0001_),
    .Q(\mem[6] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _0968_ (
    .CLK(clk),
    .D(_0132_),
    .DE(_0001_),
    .Q(\mem[6] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _0969_ (
    .CLK(clk),
    .D(_0133_),
    .DE(_0001_),
    .Q(\mem[6] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _0970_ (
    .CLK(clk),
    .D(_0134_),
    .DE(_0001_),
    .Q(\mem[6] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _0971_ (
    .CLK(clk),
    .D(_0135_),
    .DE(_0001_),
    .Q(\mem[6] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _0972_ (
    .CLK(clk),
    .D(_0136_),
    .DE(_0007_),
    .Q(\mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _0973_ (
    .CLK(clk),
    .D(_0137_),
    .DE(_0007_),
    .Q(\mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _0974_ (
    .CLK(clk),
    .D(_0138_),
    .DE(_0007_),
    .Q(\mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _0975_ (
    .CLK(clk),
    .D(_0139_),
    .DE(_0007_),
    .Q(\mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _0976_ (
    .CLK(clk),
    .D(_0140_),
    .DE(_0007_),
    .Q(\mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _0977_ (
    .CLK(clk),
    .D(_0141_),
    .DE(_0007_),
    .Q(\mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _0978_ (
    .CLK(clk),
    .D(_0142_),
    .DE(_0007_),
    .Q(\mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _0979_ (
    .CLK(clk),
    .D(_0143_),
    .DE(_0007_),
    .Q(\mem[0] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _0980_ (
    .CLK(clk),
    .D(_0144_),
    .DE(_0007_),
    .Q(\mem[0] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _0981_ (
    .CLK(clk),
    .D(_0145_),
    .DE(_0007_),
    .Q(\mem[0] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _0982_ (
    .CLK(clk),
    .D(_0146_),
    .DE(_0007_),
    .Q(\mem[0] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _0983_ (
    .CLK(clk),
    .D(_0147_),
    .DE(_0007_),
    .Q(\mem[0] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _0984_ (
    .CLK(clk),
    .D(_0148_),
    .DE(_0007_),
    .Q(\mem[0] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _0985_ (
    .CLK(clk),
    .D(_0149_),
    .DE(_0007_),
    .Q(\mem[0] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _0986_ (
    .CLK(clk),
    .D(_0150_),
    .DE(_0007_),
    .Q(\mem[0] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _0987_ (
    .CLK(clk),
    .D(_0151_),
    .DE(_0007_),
    .Q(\mem[0] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _0988_ (
    .CLK(clk),
    .D(_0152_),
    .DE(_0007_),
    .Q(\mem[0] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _0989_ (
    .CLK(clk),
    .D(_0153_),
    .DE(_0007_),
    .Q(\mem[0] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _0990_ (
    .CLK(clk),
    .D(_0154_),
    .DE(_0007_),
    .Q(\mem[0] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _0991_ (
    .CLK(clk),
    .D(_0155_),
    .DE(_0007_),
    .Q(\mem[0] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _0992_ (
    .CLK(clk),
    .D(_0156_),
    .DE(_0007_),
    .Q(\mem[0] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _0993_ (
    .CLK(clk),
    .D(_0157_),
    .DE(_0007_),
    .Q(\mem[0] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _0994_ (
    .CLK(clk),
    .D(_0158_),
    .DE(_0007_),
    .Q(\mem[0] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _0995_ (
    .CLK(clk),
    .D(_0159_),
    .DE(_0007_),
    .Q(\mem[0] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _0996_ (
    .CLK(clk),
    .D(_0160_),
    .DE(_0007_),
    .Q(\mem[0] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _0997_ (
    .CLK(clk),
    .D(_0161_),
    .DE(_0007_),
    .Q(\mem[0] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _0998_ (
    .CLK(clk),
    .D(_0162_),
    .DE(_0007_),
    .Q(\mem[0] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _0999_ (
    .CLK(clk),
    .D(_0163_),
    .DE(_0007_),
    .Q(\mem[0] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _1000_ (
    .CLK(clk),
    .D(_0164_),
    .DE(_0007_),
    .Q(\mem[0] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _1001_ (
    .CLK(clk),
    .D(_0165_),
    .DE(_0007_),
    .Q(\mem[0] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _1002_ (
    .CLK(clk),
    .D(_0166_),
    .DE(_0007_),
    .Q(\mem[0] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _1003_ (
    .CLK(clk),
    .D(_0167_),
    .DE(_0007_),
    .Q(\mem[0] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _1004_ (
    .CLK(clk),
    .D(_0168_),
    .DE(_0002_),
    .Q(\mem[5] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _1005_ (
    .CLK(clk),
    .D(_0169_),
    .DE(_0002_),
    .Q(\mem[5] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _1006_ (
    .CLK(clk),
    .D(_0170_),
    .DE(_0002_),
    .Q(\mem[5] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _1007_ (
    .CLK(clk),
    .D(_0171_),
    .DE(_0002_),
    .Q(\mem[5] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _1008_ (
    .CLK(clk),
    .D(_0172_),
    .DE(_0002_),
    .Q(\mem[5] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _1009_ (
    .CLK(clk),
    .D(_0173_),
    .DE(_0002_),
    .Q(\mem[5] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _1010_ (
    .CLK(clk),
    .D(_0174_),
    .DE(_0002_),
    .Q(\mem[5] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _1011_ (
    .CLK(clk),
    .D(_0175_),
    .DE(_0002_),
    .Q(\mem[5] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _1012_ (
    .CLK(clk),
    .D(_0176_),
    .DE(_0002_),
    .Q(\mem[5] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _1013_ (
    .CLK(clk),
    .D(_0177_),
    .DE(_0002_),
    .Q(\mem[5] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _1014_ (
    .CLK(clk),
    .D(_0178_),
    .DE(_0002_),
    .Q(\mem[5] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _1015_ (
    .CLK(clk),
    .D(_0179_),
    .DE(_0002_),
    .Q(\mem[5] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _1016_ (
    .CLK(clk),
    .D(_0180_),
    .DE(_0002_),
    .Q(\mem[5] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _1017_ (
    .CLK(clk),
    .D(_0181_),
    .DE(_0002_),
    .Q(\mem[5] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _1018_ (
    .CLK(clk),
    .D(_0182_),
    .DE(_0002_),
    .Q(\mem[5] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _1019_ (
    .CLK(clk),
    .D(_0183_),
    .DE(_0002_),
    .Q(\mem[5] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _1020_ (
    .CLK(clk),
    .D(_0184_),
    .DE(_0002_),
    .Q(\mem[5] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _1021_ (
    .CLK(clk),
    .D(_0185_),
    .DE(_0002_),
    .Q(\mem[5] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _1022_ (
    .CLK(clk),
    .D(_0186_),
    .DE(_0002_),
    .Q(\mem[5] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _1023_ (
    .CLK(clk),
    .D(_0187_),
    .DE(_0002_),
    .Q(\mem[5] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _1024_ (
    .CLK(clk),
    .D(_0188_),
    .DE(_0002_),
    .Q(\mem[5] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _1025_ (
    .CLK(clk),
    .D(_0189_),
    .DE(_0002_),
    .Q(\mem[5] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _1026_ (
    .CLK(clk),
    .D(_0190_),
    .DE(_0002_),
    .Q(\mem[5] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _1027_ (
    .CLK(clk),
    .D(_0191_),
    .DE(_0002_),
    .Q(\mem[5] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _1028_ (
    .CLK(clk),
    .D(_0192_),
    .DE(_0002_),
    .Q(\mem[5] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _1029_ (
    .CLK(clk),
    .D(_0193_),
    .DE(_0002_),
    .Q(\mem[5] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _1030_ (
    .CLK(clk),
    .D(_0194_),
    .DE(_0002_),
    .Q(\mem[5] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _1031_ (
    .CLK(clk),
    .D(_0195_),
    .DE(_0002_),
    .Q(\mem[5] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _1032_ (
    .CLK(clk),
    .D(_0196_),
    .DE(_0002_),
    .Q(\mem[5] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _1033_ (
    .CLK(clk),
    .D(_0197_),
    .DE(_0002_),
    .Q(\mem[5] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _1034_ (
    .CLK(clk),
    .D(_0198_),
    .DE(_0002_),
    .Q(\mem[5] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _1035_ (
    .CLK(clk),
    .D(_0199_),
    .DE(_0002_),
    .Q(\mem[5] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _1036_ (
    .CLK(clk),
    .D(_0200_),
    .DE(_0006_),
    .Q(\mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _1037_ (
    .CLK(clk),
    .D(_0201_),
    .DE(_0006_),
    .Q(\mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _1038_ (
    .CLK(clk),
    .D(_0202_),
    .DE(_0006_),
    .Q(\mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _1039_ (
    .CLK(clk),
    .D(_0203_),
    .DE(_0006_),
    .Q(\mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _1040_ (
    .CLK(clk),
    .D(_0204_),
    .DE(_0006_),
    .Q(\mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _1041_ (
    .CLK(clk),
    .D(_0205_),
    .DE(_0006_),
    .Q(\mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _1042_ (
    .CLK(clk),
    .D(_0206_),
    .DE(_0006_),
    .Q(\mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _1043_ (
    .CLK(clk),
    .D(_0207_),
    .DE(_0006_),
    .Q(\mem[1] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _1044_ (
    .CLK(clk),
    .D(_0208_),
    .DE(_0006_),
    .Q(\mem[1] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _1045_ (
    .CLK(clk),
    .D(_0209_),
    .DE(_0006_),
    .Q(\mem[1] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _1046_ (
    .CLK(clk),
    .D(_0210_),
    .DE(_0006_),
    .Q(\mem[1] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _1047_ (
    .CLK(clk),
    .D(_0211_),
    .DE(_0006_),
    .Q(\mem[1] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _1048_ (
    .CLK(clk),
    .D(_0212_),
    .DE(_0006_),
    .Q(\mem[1] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _1049_ (
    .CLK(clk),
    .D(_0213_),
    .DE(_0006_),
    .Q(\mem[1] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _1050_ (
    .CLK(clk),
    .D(_0214_),
    .DE(_0006_),
    .Q(\mem[1] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _1051_ (
    .CLK(clk),
    .D(_0215_),
    .DE(_0006_),
    .Q(\mem[1] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _1052_ (
    .CLK(clk),
    .D(_0216_),
    .DE(_0006_),
    .Q(\mem[1] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _1053_ (
    .CLK(clk),
    .D(_0217_),
    .DE(_0006_),
    .Q(\mem[1] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _1054_ (
    .CLK(clk),
    .D(_0218_),
    .DE(_0006_),
    .Q(\mem[1] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _1055_ (
    .CLK(clk),
    .D(_0219_),
    .DE(_0006_),
    .Q(\mem[1] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _1056_ (
    .CLK(clk),
    .D(_0220_),
    .DE(_0006_),
    .Q(\mem[1] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _1057_ (
    .CLK(clk),
    .D(_0221_),
    .DE(_0006_),
    .Q(\mem[1] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _1058_ (
    .CLK(clk),
    .D(_0222_),
    .DE(_0006_),
    .Q(\mem[1] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _1059_ (
    .CLK(clk),
    .D(_0223_),
    .DE(_0006_),
    .Q(\mem[1] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _1060_ (
    .CLK(clk),
    .D(_0224_),
    .DE(_0006_),
    .Q(\mem[1] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _1061_ (
    .CLK(clk),
    .D(_0225_),
    .DE(_0006_),
    .Q(\mem[1] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _1062_ (
    .CLK(clk),
    .D(_0226_),
    .DE(_0006_),
    .Q(\mem[1] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _1063_ (
    .CLK(clk),
    .D(_0227_),
    .DE(_0006_),
    .Q(\mem[1] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _1064_ (
    .CLK(clk),
    .D(_0228_),
    .DE(_0006_),
    .Q(\mem[1] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _1065_ (
    .CLK(clk),
    .D(_0229_),
    .DE(_0006_),
    .Q(\mem[1] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _1066_ (
    .CLK(clk),
    .D(_0230_),
    .DE(_0006_),
    .Q(\mem[1] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _1067_ (
    .CLK(clk),
    .D(_0231_),
    .DE(_0006_),
    .Q(\mem[1] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _1068_ (
    .CLK(clk),
    .D(_0232_),
    .DE(_0000_),
    .Q(\mem[7] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _1069_ (
    .CLK(clk),
    .D(_0233_),
    .DE(_0000_),
    .Q(\mem[7] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _1070_ (
    .CLK(clk),
    .D(_0234_),
    .DE(_0000_),
    .Q(\mem[7] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _1071_ (
    .CLK(clk),
    .D(_0235_),
    .DE(_0000_),
    .Q(\mem[7] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _1072_ (
    .CLK(clk),
    .D(_0236_),
    .DE(_0000_),
    .Q(\mem[7] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _1073_ (
    .CLK(clk),
    .D(_0237_),
    .DE(_0000_),
    .Q(\mem[7] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _1074_ (
    .CLK(clk),
    .D(_0238_),
    .DE(_0000_),
    .Q(\mem[7] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _1075_ (
    .CLK(clk),
    .D(_0239_),
    .DE(_0000_),
    .Q(\mem[7] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _1076_ (
    .CLK(clk),
    .D(_0240_),
    .DE(_0000_),
    .Q(\mem[7] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _1077_ (
    .CLK(clk),
    .D(_0241_),
    .DE(_0000_),
    .Q(\mem[7] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _1078_ (
    .CLK(clk),
    .D(_0242_),
    .DE(_0000_),
    .Q(\mem[7] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _1079_ (
    .CLK(clk),
    .D(_0243_),
    .DE(_0000_),
    .Q(\mem[7] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _1080_ (
    .CLK(clk),
    .D(_0244_),
    .DE(_0000_),
    .Q(\mem[7] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _1081_ (
    .CLK(clk),
    .D(_0245_),
    .DE(_0000_),
    .Q(\mem[7] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _1082_ (
    .CLK(clk),
    .D(_0246_),
    .DE(_0000_),
    .Q(\mem[7] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _1083_ (
    .CLK(clk),
    .D(_0247_),
    .DE(_0000_),
    .Q(\mem[7] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _1084_ (
    .CLK(clk),
    .D(_0248_),
    .DE(_0000_),
    .Q(\mem[7] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _1085_ (
    .CLK(clk),
    .D(_0249_),
    .DE(_0000_),
    .Q(\mem[7] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _1086_ (
    .CLK(clk),
    .D(_0250_),
    .DE(_0000_),
    .Q(\mem[7] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _1087_ (
    .CLK(clk),
    .D(_0251_),
    .DE(_0000_),
    .Q(\mem[7] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _1088_ (
    .CLK(clk),
    .D(_0252_),
    .DE(_0000_),
    .Q(\mem[7] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _1089_ (
    .CLK(clk),
    .D(_0253_),
    .DE(_0000_),
    .Q(\mem[7] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _1090_ (
    .CLK(clk),
    .D(_0254_),
    .DE(_0000_),
    .Q(\mem[7] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _1091_ (
    .CLK(clk),
    .D(_0255_),
    .DE(_0000_),
    .Q(\mem[7] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _1092_ (
    .CLK(clk),
    .D(_0256_),
    .DE(_0000_),
    .Q(\mem[7] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _1093_ (
    .CLK(clk),
    .D(_0257_),
    .DE(_0000_),
    .Q(\mem[7] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _1094_ (
    .CLK(clk),
    .D(_0258_),
    .DE(_0000_),
    .Q(\mem[7] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _1095_ (
    .CLK(clk),
    .D(_0259_),
    .DE(_0000_),
    .Q(\mem[7] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _1096_ (
    .CLK(clk),
    .D(_0260_),
    .DE(_0000_),
    .Q(\mem[7] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _1097_ (
    .CLK(clk),
    .D(_0261_),
    .DE(_0000_),
    .Q(\mem[7] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _1098_ (
    .CLK(clk),
    .D(_0262_),
    .DE(_0000_),
    .Q(\mem[7] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _1099_ (
    .CLK(clk),
    .D(_0263_),
    .DE(_0000_),
    .Q(\mem[7] [31])
  );
endmodule

module \$paramod\ff_2_sync\SIZE=s32'00000000000000000000000000000011 (clk, rst_n, din, dout);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [2:0] din;
  wire [2:0] din;
  output [2:0] dout;
  wire [2:0] dout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [2:0] ff_1;
  sky130_fd_sc_hd__and2_0 _06_ (
    .A(din[0]),
    .B(rst_n),
    .X(_00_)
  );
  sky130_fd_sc_hd__and2_0 _07_ (
    .A(rst_n),
    .B(din[1]),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_0 _08_ (
    .A(rst_n),
    .B(din[2]),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _09_ (
    .A(rst_n),
    .B(ff_1[0]),
    .X(_03_)
  );
  sky130_fd_sc_hd__and2_0 _10_ (
    .A(rst_n),
    .B(ff_1[1]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and2_0 _11_ (
    .A(rst_n),
    .B(ff_1[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(clk),
    .D(_00_),
    .Q(ff_1[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(clk),
    .D(_01_),
    .Q(ff_1[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(_02_),
    .Q(ff_1[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(_03_),
    .Q(dout[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_04_),
    .Q(dout[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_05_),
    .Q(dout[2])
  );
endmodule

module \$paramod\rd_ptr\SIZE=s32'00000000000000000000000000000011 (clk, rst_n, rd_en, ptr_g_in, ptr_g_out, ptr_b_out, empty);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input rd_en;
  wire rd_en;
  input [2:0] ptr_g_in;
  wire [2:0] ptr_g_in;
  output [2:0] ptr_g_out;
  wire [2:0] ptr_g_out;
  output [2:0] ptr_b_out;
  wire [2:0] ptr_b_out;
  output empty;
  wire empty;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(rd_en),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21bo_1 _25_ (
    .A1(ptr_b_out[1]),
    .A2(ptr_b_out[0]),
    .B1_N(ptr_b_out[2]),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(ptr_b_out[1]),
    .B(ptr_b_out[0]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _27_ (
    .A(ptr_b_out[2]),
    .SLEEP(_07_),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand3b_1 _28_ (
    .A_N(ptr_b_out[2]),
    .B(ptr_b_out[1]),
    .C(ptr_b_out[0]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__and2_0 _29_ (
    .A(_06_),
    .B(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__and3_1 _30_ (
    .A(_06_),
    .B(_07_),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _31_ (
    .A(_08_),
    .SLEEP(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__o21ai_0 _32_ (
    .A1(_08_),
    .A2(_11_),
    .B1(ptr_g_in[1]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(ptr_g_in[2]),
    .B(_10_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xor2_1 _34_ (
    .A(ptr_b_out[1]),
    .B(ptr_g_in[0]),
    .X(_15_)
  );
  sky130_fd_sc_hd__o21a_1 _35_ (
    .A1(ptr_g_in[2]),
    .A2(_10_),
    .B1(_15_),
    .X(_16_)
  );
  sky130_fd_sc_hd__or3_1 _36_ (
    .A(ptr_g_in[1]),
    .B(_08_),
    .C(_11_),
    .X(_17_)
  );
  sky130_fd_sc_hd__and4_1 _37_ (
    .A(_13_),
    .B(_14_),
    .C(_16_),
    .D(_17_),
    .X(empty)
  );
  sky130_fd_sc_hd__a41oi_1 _38_ (
    .A1(_13_),
    .A2(_14_),
    .A3(_16_),
    .A4(_17_),
    .B1(_05_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o21ai_0 _39_ (
    .A1(ptr_b_out[0]),
    .A2(_18_),
    .B1(rst_n),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a21oi_1 _40_ (
    .A1(ptr_b_out[0]),
    .A2(_18_),
    .B1(_19_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__o21ai_0 _41_ (
    .A1(ptr_b_out[1]),
    .A2(_18_),
    .B1(rst_n),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _42_ (
    .A1(_07_),
    .A2(_18_),
    .B1(_20_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__o21ai_0 _43_ (
    .A1(ptr_g_out[0]),
    .A2(_18_),
    .B1(rst_n),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a21oi_1 _44_ (
    .A1(ptr_b_out[1]),
    .A2(_18_),
    .B1(_21_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21ai_0 _45_ (
    .A1(ptr_g_out[1]),
    .A2(_18_),
    .B1(rst_n),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a21oi_1 _46_ (
    .A1(_12_),
    .A2(_18_),
    .B1(_22_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _47_ (
    .A1(ptr_b_out[2]),
    .A2(_18_),
    .B1(rst_n),
    .Y(_23_)
  );
  sky130_fd_sc_hd__a21oi_1 _48_ (
    .A1(_10_),
    .A2(_18_),
    .B1(_23_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_00_),
    .Q(ptr_b_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_01_),
    .Q(ptr_b_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_02_),
    .Q(ptr_g_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_03_),
    .Q(ptr_g_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_04_),
    .Q(ptr_b_out[2])
  );
  assign ptr_g_out[2] = ptr_b_out[2];
endmodule

module \$paramod\wtr_ptr\SIZE=s32'00000000000000000000000000000011 (clk, rst_n, wtr_en, ptr_g_in, ptr_g_out, ptr_b_out, full);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input wtr_en;
  wire wtr_en;
  input [2:0] ptr_g_in;
  wire [2:0] ptr_g_in;
  output [2:0] ptr_g_out;
  wire [2:0] ptr_g_out;
  output [2:0] ptr_b_out;
  wire [2:0] ptr_b_out;
  output full;
  wire full;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(ptr_g_in[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(wtr_en),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21boi_0 _28_ (
    .A1(ptr_b_out[1]),
    .A2(ptr_b_out[0]),
    .B1_N(ptr_b_out[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(ptr_b_out[1]),
    .B(ptr_b_out[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2_0 _30_ (
    .A(ptr_b_out[2]),
    .B(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__and3b_1 _31_ (
    .A_N(ptr_b_out[2]),
    .B(ptr_b_out[1]),
    .C(ptr_b_out[0]),
    .X(_10_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _32_ (
    .A(_07_),
    .SLEEP(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _33_ (
    .A(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor3_1 _34_ (
    .A(_07_),
    .B(_08_),
    .C(_10_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _35_ (
    .A(_09_),
    .SLEEP(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _36_ (
    .A1(_09_),
    .A2(_13_),
    .B1(_05_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__or3_1 _37_ (
    .A(ptr_g_in[2]),
    .B(_07_),
    .C(_10_),
    .X(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(ptr_b_out[1]),
    .B(ptr_g_in[0]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _39_ (
    .A1(ptr_g_in[2]),
    .A2(_11_),
    .B1(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__or3_1 _40_ (
    .A(_05_),
    .B(_09_),
    .C(_13_),
    .X(_19_)
  );
  sky130_fd_sc_hd__and4_1 _41_ (
    .A(_15_),
    .B(_16_),
    .C(_18_),
    .D(_19_),
    .X(full)
  );
  sky130_fd_sc_hd__a41oi_1 _42_ (
    .A1(_15_),
    .A2(_16_),
    .A3(_18_),
    .A4(_19_),
    .B1(_06_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _43_ (
    .A1(ptr_b_out[0]),
    .A2(_20_),
    .B1(rst_n),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a21oi_1 _44_ (
    .A1(ptr_b_out[0]),
    .A2(_20_),
    .B1(_21_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__mux2i_1 _45_ (
    .A0(ptr_b_out[1]),
    .A1(_08_),
    .S(_20_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _46_ (
    .A(rst_n),
    .SLEEP(_22_),
    .X(_01_)
  );
  sky130_fd_sc_hd__o21ai_0 _47_ (
    .A1(ptr_g_out[0]),
    .A2(_20_),
    .B1(rst_n),
    .Y(_23_)
  );
  sky130_fd_sc_hd__a21oi_1 _48_ (
    .A1(ptr_b_out[1]),
    .A2(_20_),
    .B1(_23_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21ai_0 _49_ (
    .A1(ptr_g_out[1]),
    .A2(_20_),
    .B1(rst_n),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a21oi_1 _50_ (
    .A1(_14_),
    .A2(_20_),
    .B1(_24_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _51_ (
    .A1(ptr_b_out[2]),
    .A2(_20_),
    .B1(rst_n),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21oi_1 _52_ (
    .A1(_12_),
    .A2(_20_),
    .B1(_25_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_00_),
    .Q(ptr_b_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_01_),
    .Q(ptr_b_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_02_),
    .Q(ptr_g_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_03_),
    .Q(ptr_g_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_04_),
    .Q(ptr_b_out[2])
  );
  assign ptr_g_out[2] = ptr_b_out[2];
endmodule

module async_fifo(clk, rst_n, data_in, wtr_en, rd_en, full, empty, data_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [31:0] data_in;
  wire [31:0] data_in;
  input wtr_en;
  wire wtr_en;
  input rd_en;
  wire rd_en;
  output full;
  wire full;
  output empty;
  wire empty;
  output [31:0] data_out;
  wire [31:0] data_out;
  wire [2:0] rd_b_ptr;
  wire [2:0] rd_g_ptr;
  wire [2:0] rd_g_ptr_ff;
  wire [2:0] wtr_b_ptr;
  wire [2:0] wtr_g_ptr;
  wire [2:0] wtr_g_ptr_ff;
  \$paramod\ff_2_sync\SIZE=s32'00000000000000000000000000000011  ff_2_read (
    .clk(clk),
    .din(rd_g_ptr),
    .dout(rd_g_ptr_ff),
    .rst_n(rst_n)
  );
  \$paramod\ff_2_sync\SIZE=s32'00000000000000000000000000000011  ff_2_write (
    .clk(clk),
    .din(wtr_g_ptr),
    .dout(wtr_g_ptr_ff),
    .rst_n(rst_n)
  );
  \$paramod$c187add8a104ddaa470efe8146e8110778d2ccf0\mem  memory (
    .clk(clk),
    .data_in(data_in),
    .data_out(data_out),
    .empty(empty),
    .full(full),
    .rd_en(rd_en),
    .rd_ptr(rd_b_ptr),
    .rst_n(rst_n),
    .wtr_en(wtr_en),
    .wtr_ptr(wtr_b_ptr)
  );
  \$paramod\rd_ptr\SIZE=s32'00000000000000000000000000000011  read_pointer (
    .clk(clk),
    .empty(empty),
    .ptr_b_out(rd_b_ptr),
    .ptr_g_in(wtr_g_ptr_ff),
    .ptr_g_out(rd_g_ptr),
    .rd_en(rd_en),
    .rst_n(rst_n)
  );
  \$paramod\wtr_ptr\SIZE=s32'00000000000000000000000000000011  write_pointer (
    .clk(clk),
    .full(full),
    .ptr_b_out(wtr_b_ptr),
    .ptr_g_in(rd_g_ptr_ff),
    .ptr_g_out(wtr_g_ptr),
    .rst_n(rst_n),
    .wtr_en(wtr_en)
  );
endmodule
